import { supabaseAdmin } from "@/lib/supabaseAdmin";
import { NextRequest, NextResponse } from "next/server";
import { withAuth } from "@/lib/api-auth";

/**
 * Bulk import policies from the StandardPolicy JSON format.
 * Accepts an array of policy objects (as generated by the PDF extraction).
 * Upserts on (org_id, policy_id) so re-importing is safe.
 */
export const POST = withAuth(async (req: NextRequest, ctx) => {
  const body = await req.json();
  const policies: unknown[] = Array.isArray(body) ? body : body.policies;
  if (!policies || !policies.length) {
    return NextResponse.json({ error: "No policies provided" }, { status: 400 });
  }

  // Map from StandardPolicy JSON format → DB row format
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const rows = policies.map((p: any) => ({
    org_id: ctx.orgId,
    policy_id: p.id,
    version: p.version ?? "1.0.0",
    status: p.status ?? "draft",
    domain: p.domain,
    subdomain: p.subdomain,
    tags: p.tags ?? [],
    rule_statement: p.rule?.statement ?? "",
    rule_rationale: p.rule?.rationale ?? "",
    rule_severity: p.rule?.severity ?? "warning",
    rule_examples: p.rule?.examples ?? {},
    scope: p.scope ?? {},
    remediation_hint: p.remediation?.hint ?? "",
    remediation_docs_url: p.remediation?.docs_url ?? null,
    provenance: p.provenance ?? {},
    created_by: ctx.user.id,
    approved_at: p.lifecycle?.approved_at ?? null,
    approved_by: p.lifecycle?.approved_by ?? null,
    review_date: p.lifecycle?.review_date ?? null,
    source_document: p.provenance?.sources?.[0]?.ref ?? null,
    source_section: p.provenance?.sources?.[0]?.section ?? null,
  }));

  const { data, error } = await supabaseAdmin
    .from("standard_policies")
    .upsert(rows, { onConflict: "org_id,policy_id" })
    .select();

  if (error) {
    console.error("[standard-policies/import POST]", error);
    return NextResponse.json({ error: error.message }, { status: 400 });
  }

  return NextResponse.json({ data, count: data?.length ?? 0 });
});
